### PR TITLE
twitter bot for ubiquity

### PR DESCRIPTION
**Pull request by ManyRios**
https://github.com/ubiquity/bounty-bot/issues/55 and https://github.com/ubiquity/bounty-bot/issues/56

### CODE REVIEW

**Comment by 0xcodercrane** [comment]
I am gonna holding off this PR until the [PR](https://github.com/ubiquity/bounty-bot/pull/75) merged into development. The reason why that PR has the base architecture for adapters like supabase, telegram, etc.

**Comment by ManyRios** [comment]
It's ok now @pavlovcik ?

**Comment by ManyRios** [comment]
What now @0xcodercrane ?

**Comment by ManyRios** [comment]
@0xcodercrane

**Pull request closed without merging**
