### PR TITLE
bot and interface for ubiquity twitter

### PR DESCRIPTION
**Pull request by ManyRios**
First PR for these bounties https://github.com/ubiquity/bounty-bot/issues/56 and https://github.com/ubiquity/bounty-bot/issues/55

### CODE REVIEW

**Comment by Steveantor** [comment]
This PR brings its own `package.json` `tsconfig.json` and other deps-config files.
Not the ideal behavior.

**Comment by ManyRios** [comment]
Hi, what it you mean with not ideal behavior?

**Comment by Steveantor** [comment]
> Hi, what it you mean with not ideal behavior?

there should only be a single `package.json` for this project.

**Comment by ManyRios** [comment]
I noticed it. I'm fixing it thanks

**Comment by ManyRios** [comment]
Changes made... waiting for your feedback

**Comment by pavlovcik** [comment]
> Changes made... waiting for your feedback

Perhaps the instructions were unclear. I'm looking now and it appears that you currently have

`package.json` and `src/package.json` right now. You should only have a single `package.json` file in the whole project.

You also have two `yarn.lock` files.

**Comment by ManyRios** [comment]
> > Changes made... waiting for your feedback
> 
> Perhaps the instructions were unclear. I'm looking now and it appears that you currently have
> 
> `package.json` and `src/package.json` right now. You should only have a single `package.json` file in the whole project.
> 
> You also have two `yarn.lock` files.

No, that was clear... but is my bad

**Comment by ManyRios** [comment]
I made a new PR

**Pull request closed without merging**
