### PR TITLE
GitHub ratelimit

### LINKED ISSUE #134: Rate Limit Header
It would be better to read the rate limit header that's passed with the GitHub response and change behavior based on that number I think. 

_Originally posted by @pavlovcik in https://github.com/ubiquity/bounty-bot/pull/129#discussion_r1115189897_

### PR DESCRIPTION
**Pull request by devpanther**
Fixes #134

### CODE REVIEW

**Review by pavlovcik — APPROVED** [review]

**Review by 0xcodercrane — CHANGES_REQUESTED** [review]
I will review this PR more deeply cause it seems not including all the GitHub API requests. 
Let me keep @devpanther updated on that

**Comment by pavlovcik** [comment]
> > it seems not including all the GitHub API requests.
> 
> I don't get what you mean

I think what @0xcodercrane means is that your implementation should be a general utility function that we call before every request to any GitHub API endpoint across all of the features of the bot.

**Comment by devpanther** [comment]
> > > it seems not including all the GitHub API requests.
> > 
> > 
> > I don't get what you mean
> 
> I think what @0xcodercrane means is that your implementation should be a general utility function that we call before every request to any GitHub API endpoint across all of the features of the bot.

I think that's the only time Github API is called and requires a rate limiter, all other requests are POSTs (fetching issues and removing/adding assignees)..

**Comment by devpanther** [comment]
Screenshot 2023-04-11 at 10 22 39 AM
This allowed @pavlovcik

**Comment by 0xcodercrane** [comment]
> I think what @0xcodercrane means is that your implementation should be a general utility function that we call before every request to any GitHub API endpoint across all of the features of the bot.

Yep! exactly!  That's originally what I want. by the way, it sounds wrong its the only place where the Github API is called. 

We have a couple of files more to call Github API. Please take a look at the following example files.
https://github.com/ubiquity/bounty-bot/blob/development/src/helpers/issue.ts
https://github.com/ubiquity/bounty-bot/blob/development/src/helpers/label.ts

**Comment by devpanther** [comment]
Okay, will check em out.. Thanks

**Comment by devpanther** [comment]
@0xcodercrane i see issue file requires a retry.. but is there any need to do that in the label file.

They're just post/get requests called once unlike the get requests in a while loop

**Pull request merged**
