### PR TITLE
Weekly Summary Enhancements

### LINKED ISSUE #119: Enhance Weekly Summary
https://t.me/ubtestingchannel/55 UB Testing Channel, [Feb 12, 2023 at 19:57]
new issues: 7
issues resolved: 6
total user interactions count: 68
bounties given: 1000 USD
new pulls: 11
closed pulls: 4
merged pulls: 6
total commits: 279

---

New schema, no monospace font:

📝 commits: 279 
📂 issues opened: 7
📁 issues closed: 6
📄 pull requests: 11
📑 pull requests merged: 6

---

Also we should use Proxima Nova font on the rendered image.

### PR DESCRIPTION
**Pull request by Steveantor**
Resolves #119

### CODE REVIEW

**Comment by pavlovcik** [comment]
Can you link me a test Telegram message? You should be able to share the direct message link from the test group. That can serve as the "test" for this PR.

**Comment by pavlovcik** [comment]
https://t.me/ubtestingchannel/56

I hope the stats are actually working but the formatting looks better.

**Comment by Steveantor** [comment]
@pavlovcik is there anything that needs to be done here? 
dealing with merge conflicts each day.

**Comment by pavlovcik** [comment]
Hey @Steveantor it looks great in the channel. My last request is that it seems that you mashed together the separate lines in the plaintext report. https://t.me/ubtestingchannel/59

```
We achieved a lot in the last 14 days! 💪
We refactored the code to pass a cspell check, added a coverage check to our CI workflow, and updated the Node version to 18.We also created a Railway deployment script and fixed several bugs, including ones related to credit redemption and updating total debt.
Great job everyone! Keep up the good work!
```

For example I see issues with the period ending the sentence touching the first letter of the next sentence. 

Upon closer inspection I see it only once in this particular report. But be sure to fix as it will be more prominent with longer reports with more sentences. After that I promise to merge asap!

**Comment by Steveantor** [comment]
> Hey @Steveantor it looks great in the channel. My last request is that it seems that you mashed together the separate lines in the plaintext report. https://t.me/ubtestingchannel/59
> 
> ```
> We achieved a lot in the last 14 days! 💪
> We refactored the code to pass a cspell check, added a coverage check to our CI workflow, and updated the Node version to 18.We also created a Railway deployment script and fixed several bugs, including ones related to credit redemption and updating total debt.
> Great job everyone! Keep up the good work!
> ```
> 
> For example I see issues with the period ending the sentence touching the first letter of the next sentence.
> 
> Upon closer inspection I see it only once in this particular report. But be sure to fix as it will be more prominent with longer reports with more sentences. After that I promise to merge asap!

updated the regex

**Review by pavlovcik — APPROVED** [review]

**Comment by pavlovcik** [comment]
I can't auto-merge or merge due to conflicts but I'm ready to merge as soon as the conflicts are remedied. Feel free to merge if you have the authority to.

**Comment by Steveantor** [comment]
> I can't auto-merge or merge due to conflicts but I'm ready to merge as soon as the conflicts are remedied. Feel free to merge if you have the authority to.

okay, I've merged it @pavlovcik

**Pull request merged**
